### ISSUE TITLE
Silent's Gems recipes are missing in JEI

### ISSUE THREAD

**Issue by DennHenda** [CreativeMD/InGameConfigManager#40]
When installing Creative Core, Silent Lib, IGCM, Silent's Gems, and JEI the recipes for tools, weapons, armor, etc. are hidden in JEI. The items are still craftable. 

Silent's Gems has a modular crafting system that allows mixed materials, from what I understand the recipes are all just one recipe.

This occurs in a fresh install without altering any recipes. 

Forge 1.12.2 - 14.23.4.2745

Creative Core 1.9.25
IGCM 1.2.2
JEI 4.11.0.202
Silent Lib 2.3.1-107
Silent's Gems 2.7.4-272

**Comment by Naxdar** [comment]
Similarly, adding IGCM 1.2.3 to my modpack is breaking the listing of crafttweaker script recipes in JEI.

**Comment by CreativeMD** [comment]
@Naxdar I can't change anything about the crafttweaker issue, you can use IGCM to add recipes anyway.
@DennHenda Silent Gems adds its recipe in a weird way. JEI does not recognize them, so there is no connection between the actual recipes and the ones you can see in JEI. They are added separately by Silent Gems ([source](https://github.com/SilentChaos512/SilentGems/blob/aa3bb81c5f905bfda74ac84970893414925aef3a/src/main/java/net/silentchaos512/gems/compat/jei/SilentGemsPlugin.java#L52)). That's why they get lost.

Can you do me a favor and search for "silentgem" recipes in IGCM (disable workbench recipes), I can't do it at the moment. It would allow me to know whether the recipes should be added to JEI or not (otherwise if you disable them they would still be visible in JEI).

**Comment by DennHenda** [comment]
![2018-08-12_14 20 05](https://user-images.githubusercontent.com/19595171/44005583-4c5fd380-9e3b-11e8-926c-b527faa997fd.png)

It shows that there are recipes, although they are all blank for tools.  Disabling them doesn't seem to change anything.  All of the other items in Silent's Gems are in the list and working fine, it's strictly items that include gems, seems like it just has something to do with the way you can use any gem in those recipes.

I have contacted the author of Silent's Gems, if you think there's something they could do to fix it in their source.  Also, the Silent's Gems mod seems to be going through an overhaul (the crafting system is changing entirely), so it may be fixed in a later release anyway.

**Comment by CreativeMD** [comment]
Sorry, for not respond earlier, but this version should do it:
https://www.dropbox.com/s/58yui5pnu84zk05/IGCM_v1.2.5_mc1.12.2.jar?dl=1

Can you test it?

**Comment by CreativeMD** [comment]
Any updates?

**Comment by CreativeMD** [comment]
I will close this issue for now, if the issue still persists just let me know and reopen the issue.

**Comment by Trinsdar** [comment]
So @CreativeMD this issue also occurs for simple logic wires and gates: https://github.com/CharsetMC/Charset/issues/387 Seems like disabling the crafting module fixes it.

**Comment by CreativeMD** [comment]
Can you open a new issue of it?

**Comment by Trinsdar** [comment]
Sure
